webRunes/Core-WRIO-App

widget/create.htm
widget/create.js

https://github.com/webRunes/Core-WRIO-App/issues/1

Editor, first version

---

.travis.yml

This is against https://github.com/webRunes/Core-WRIO-App/issues/5

Adding S3 deployment configuration on .travis.yml

---

article.js
package.json
server.js
views/core.ejs

https://github.com/webRunes/Core-WRIO-App/issues/13

Edit JSON-LD #13

---

src/client/js/core.js
src/client/views/core.ejs

[#27](https://github.com/webRunes/Core-WRIO-App/issues/27)

Header and save

---

src/client/js/core.js

https://github.com/webRunes/Core-WRIO-App/pull/35

Remove mistake (Header and save)

---

src/client/js/core.js
src/client/views/core.ejs

Add "data-widget-id" field: https://github.com/webRunes/Core-WRIO-App/issues/14
Fix save filename: https://github.com/webRunes/Core-WRIO-App/issues/50

Enable comments #14

---

src/client/js/core.js
src/client/views/core.ejs

Partial resolve webRunes/Core-WRIO-App#41

Feed line replace #41

---

src/client/js/core.js

https://github.com/webRunes/Core-WRIO-App/issues/24

Save on s3 #24: add spec download method for IE

---

src/client/views/core.ejs

https://github.com/webRunes/Default-WRIO-Theme/issues/102

Core css issue #102: increase width textarea

---

Dockerfile
gulpfile.js
package.json
src/client/js/core.js

https://github.com/webRunes/Core-WRIO-App/issues/64

Widget #64 Fixed save feature, added check if user allowed to save to specified location, if not - save button disabled

---

src/client/js/core.js

File extension txt->htm

---

src/client/js/core.js

https://github.com/webRunes/Core-WRIO-App/issues/85

Add noscript feature #85

---

src/client/js/client.js

STORAGE_DOMAIN fix

---

src/client/js/client.js

Profile URL fix

---

src/client/js/client.js
src/client/views/core.htm

Get profile query method fix

---

src/client/js/client.js
test/mention.js

https://github.com/webRunes/Core-WRIO-App/issues/64

Widget #64

---

src/client/js/client.js
src/client/js/getHttp.js

Fix core operation

---

src/client/js/client.js

https://github.com/webRunes/Core-WRIO-App/issues/120
create hotfix

draft-js #120

---

src/client/js/CommentEnabler.js
src/client/js/CoreEditor.js
src/client/js/client.js
src/client/js/customActions.js

Move commented blocks to the bottom

Core get comment widget twitter ID feature. Titter comments

---

src/client/js/CommentEnabler.js
src/client/js/CommentSaver.js
src/client/js/CoreEditor.js
src/client/js/JSONDocument.js
src/client/js/client.js
src/client/js/customActions.js
src/client/js/webrunesAPI.js
src/client/views/core.htm

Refactor, modify core base class.
Allow to hanldle multiple section LD+JSON properly. 
Base GenericLDJsonDocument for base LD+JSON operations, use JSONDocument class through all document workflow
CSS fix

Core refactoring, comment enabler

---

gulpfile.js
src/client/js/CommentSaver.js
src/client/js/CoreEditor.js
src/client/js/client.js
src/client/js/webrunesAPI.js
test/jsondoc.js
test/mention.js

Simple LD+JSON test added
Method extraction refactoring for CoreEditor's getEditorState function

Fix error when core was always getting new temporary user

---

hub/index.html

https://github.com/webRunes/WRIO-InternetOS/issues/647

htm -> html #647

---

src/client/js/client.js
src/index.js

https://github.com/webRunes/WRIO-InternetOS/issues/676

Serve entire hub directory

---

src/client/js/JSONDocument.js
src/client/js/customActions.js

the way links were stored was chagned, need to test for linkURL,
Description and Name

Save as for links

---

src/client/js/CommentSaver.js
src/client/js/CoreEditor.js
src/client/js/JSONDocument.js
src/client/js/client.js
src/client/js/getHttp.js
src/client/js/stores/texteditor.js
src/index.js

Add fault tolerance, faulty mentions won't crash app render process
Fix crash when searching loading indicator

Core bugfixing, allows to show ordinary JSON documents

---

hub/index.html

https://core.wrioos.com/?create

Redirect to ?create

---

src/client/js/CoreEditor.js
src/client/js/components/LinkUrlDialog.js
src/client/js/customActions.js

https://github.com/webRunes/Core-WRIO-App/issues/189

update UI from core-create-tmp.html

---

src/client/js/CommentEnabler.js
src/client/js/CoreEditor.js
src/client/js/actions/wrio.js
src/client/js/client.js
src/client/js/components/Postsettings.js
src/client/js/customActions.js
src/client/js/stores/wrio.js
src/client/js/webrunesAPI.js

https://github.com/webRunes/Core-WRIO-App/issues/189

#189 Automate comment creation, fix bugs, new comment UI

---

src/client/js/CommentEnabler.js
src/client/js/components/Postsettings.js

help-block position has been changed

iframe height fix for dropdown. Will be removed later

---

package.json
src/client/js/CoreEditor.js
src/client/js/EditorEntities/ImageEntitiy.js
src/client/js/EditorEntities/LinkEntity.js
src/client/js/stores/texteditor.js
src/client/views/core.html

Add missing core.css
Fix link cursor behaviour
Move cursor to the end of new document
Append http to the links without scheme

Core fixes

---

src/client/js/CoreEditor.js
src/client/js/components/Postsettings.js
src/client/js/saveActions.js
src/client/js/stores/texteditor.js
src/client/js/utils/url.js

fix underscored url's editing problem

Fix reload after publish

---

hub/offer/index.html

Formula: Reward = 1,000,000 WRG / Total amount of THX * The amount of all THX you have

Offer formula text upd

---

src/client/js/EditorEntities/SocialMediaEntity.js
src/client/js/JSONDocument.js
src/client/views/core.html

Add link support  …
Fix duplication bug

Add link support, fix duplication bug

---

src/client/js/CommentSaver.js
src/client/js/components/Postsettings.js

Fix spaces in name not converted to _ if filename entered directly

---

src/client/js/JSONDocument.js
src/client/js/utils/entitytools.js

Proper solution:
https://draftjs.org/docs/advanced-topics-block-components.html, also see the stash on local pc

Quick hack to delete empty blocks of text, to avoid it's population 

---

src/client/js/JSONDocument.js
src/client/js/stores/texteditor.js
src/client/js/stores/wrio.js
src/client/js/utils/entitytools.js

Fix mention bug for articles with empty about field
Fix comments enabled by default

Correctly delete unused blocks, don't delete blocks with entities

---

src/client/views/core-localhost.html
src/client/views/core.html

[Issues list #458](https://github.com/webRunes/Core-WRIO-App/issues/458)

Rename title Core Editor
